# Generated by Django 4.0.2 on 2022-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('moralisAddress', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
