# Generated by Django 4.0.2 on 2022-04-10 17:02

import NftGen.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NftGen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.CharField(blank=True, max_length=6, null=True)),
                ('img_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NftGen.user')),
            ],
        ),
        migrations.CreateModel(
            name='LayersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_num', models.CharField(blank=True, max_length=3, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NftGen.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=NftGen.models.get_file_path, verbose_name='File')),
                ('rarity', models.FloatField(default=0.25)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NftGen.layersmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NftGen.user')),
            ],
        ),
    ]
