# Generated by Django 4.0.2 on 2022-04-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NftGen', '0002_projectdesc_layersmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='moralisAddress',
        ),
    ]
